packages:
  - playground
  - bench
  - docs

dedupePeers: true

ignoreWorkspaceRootCheck: true

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - vue-demi

overrides:
  nuxt-precog: link:.
